### ISSUE TITLE
Armor Calculations not adding up

### ISSUE THREAD

**Issue by Pahiro** [vodofrede/erdtree#4]
I've currently got a max load of 62.5 of which 70% = 43.75 (Correctly shown as 43.8 though it might be better to round down).

As soon as I add my current equipment load, the total sums up to 49.4

Your budget calculation should be 
* (max * rollModifier ) - current
and not:
* (max - current) * rollModifier

**Comment by Pahiro** [comment]
Fixed with #5

**Comment by vodofrede** [comment]
Merged, thank you very much =)
